@echo off
:: fix_bundling.bat
cd calldeskapp
echo Deleting node_modules...
rd /s /q node_modules
echo Deleting package-lock.json...
del package-lock.json
echo Reinstalling dependencies...
call npm install
echo Starting expo with cache clear...
npx expo start --clear
